[package]
name = "misc"
version = "0.1.0"
authors = ["Steven Shaw <steven@steshaw.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
no-panic = "0.1.12"

[profile.dev]
opt-level = 1
